name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/portfolio
            
            git pull origin main
          
            sudo docker build -t terminal-portfolio .
            
            sudo docker rm -f portfolio || true
            
            sudo docker run -d -p 3000:3000 --name portfolio --restart unless-stopped terminal-portfolio:latest

            sudo docker image prune -f